{{- if .Values.grafana.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Values.grafana.name }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  # Grafana configuration
  config:
    {{- toYaml .Values.grafana.config | nindent 4 }}
{{- end }}
