# quarkus-app/values.yaml
appName: vm-test-app
namespace: victoria-test-app

replicaCount: 1

image:
  repository: quay.io/tpolacek/vm-test-app
  tag: "1.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

configmap:
  files:
    - "configs/application.properties"
