quarkus.otel.exporter.otlp.metrics.endpoint=http://vmsingle-vmsingle.victoria-metrics.svc:8428/opentelemetry
quarkus.otel.exporter.otlp.logs.endpoint=http://vlsingle-vlsingle.victoria-metrics.svc:9428/insert/opentelemetry
quarkus.otel.exporter.otlp.traces.endpoint=http://vtsingle-vtsingle.victoria-metrics.svc:10428/insert/opentelemetry
